# Use postgres/example user/password credentials
version: '3.1'

services:

  db10:
    image: "postgres:12.7-alpine"
    hostname: postgres
    ports:
      - "6543:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rewell
      
    restart: unless-stopped
    volumes: 
          - ./rewell-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          # - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql   
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
